apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: mgmt-es-cluster
  namespace: operator
spec:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.3
  elastic-search-image: upmcenterprises/docker-elasticsearch-kubernetes:6.1.3_0
  client-node-replicas: 3
  master-node-replicas: 2
  data-node-replicas: 3
  network-host: 0.0.0.0
  zones: []
  data-volume-size: 3Gi
  java-options: "-Xms512m -Xmx512m"
  snapshot:
    scheduler-enabled: false
    bucket-name: elasticsnapshots99
    cron-schedule: "@every 2m"
    image: upmcenterprises/elasticsearch-cron:0.0.4
  storage:
    storage-class: rook-block
  resources:
    requests:
      memory: 1024Mi
      cpu: 1000m
    limits:
      memory: 2048Mi
      cpu: '1'
